version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dj_arbuz_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: utiputi
      POSTGRES_DB: users_database
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
